<?php
if ( !is_user_logged_in() ) {
	wp_redirect( site_url());
	exit;
}
$version = get_bloginfo( 'version' ); ?>

<html>
<head>
	<link rel='stylesheet' id='login-css' href='<?php echo get_template_directory_uri() . '/stylesheets/2FA.css' ?>' type='text/css' media='all'/>

	<link rel='stylesheet' id='login-css' href='<?php echo admin_url( '/css/login.min.css?ver=' . $version ) ?>'
	      type='text/css' media='all'/>
	<link rel='stylesheet' id='login-css'
	      href='<?php echo site_url( '/wp-includes/css/buttons.min.css?ver=' . $version ) ?>' type='text/css'
	      media='all'/>
</head>
<body class="login login-action-login wp-core-ui">

<div id="login">

	<?php


	include_once( __DIR__ . '/../GoogleAuthenticator/GoogleAuthenticator.php' );

	$ga = new PHPGangsta_GoogleAuthenticator();


	$secret = current_user_meta('2FA_secret');

	if ( ! $secret ){
		$secret = $ga->createSecret();
		update_user_meta( get_current_user_id(), '2FA_secret', $secret );
	};

	$user  = wp_get_current_user();
	$login = $user->user_login;

	$urlencoded = urlencode( 'otpauth://totp/' . $login . '?secret=' . $secret . '' );
	if ( isset( $title ) ) {
		$urlencoded .= urlencode( '&issuer=' . urlencode( $title ) );
	}
	$googleURL = 'https://chart.googleapis.com/chart?chs=120x120&chld=M|0&cht=qr&chl=' . $urlencoded . '';

	$isSetup = current_user_meta( '2FA_setup' );


	if ( isset( $_POST['OTP'] ) ) {

		$didVerify = $ga->verifyCode( $secret, $_POST['OTP'], 2 );


		if ( $didVerify  ) {
			if ( ! $isSetup ) {
				update_user_meta( get_current_user_id(), '2FA_setup', true );
			}

			$_SESSION['bisons_skip2FA'] = true;
			wp_redirect( $_GET['next'] );
			exit;
		}
	} elseif ( $_SESSION['bisons_skip2FA'] ) {
		wp_redirect( $_GET['next'] );
		exit;
	}

	?>


	<?php if ( ! $isSetup && ! $_POST)  : ?>
		<h2>Setup 2FA</h2>
		<img src="<?php echo $googleURL ?>"/>

		<p><a
				href="https://en.wikipedia.org/wiki/Two-factor_authentication">Two Factor Authentication</a> is compulsory with committee accounts. Please scan this QR code below using <a
				href="https://support.google.com/accounts/answer/1066447?hl=en">Google Authenticator<a/> or <a
					href="https://www.authy.com/">Authy</a>.</p>
<p>Once you have your code generator setup, please check it is working by entering a code in the box below. If
			it worked, you will be redirected to the page you were trying to
		 access.</p>
	<?php elseif ( ! $isSetup && ! $didVerify & $_POST ) : ?>
		<h2>Setup 2FA</h2>
		<img src="<?php echo $googleURL ?>"/>

		<p>Because you are a committee member, you are require to use <a
				href="https://en.wikipedia.org/wiki/Two-factor_authentication">Two Factor Authentication</a> to login to
			restricted areas. Please scan the QR code below using <a
				href="https://support.google.com/accounts/answer/1066447?hl=en">Google Authenticator<a/> or <a
					href="https://www.authy.com/">Authy</a>.</p>
		<div id="login_error">That didn't seem to work, please try again.</div>
	<?php elseif ( ! $didVerify && $isSetup && $_POST ) : ?>
		<h1><a href="https://wordpress.org/" title="Powered by WordPress" tabindex="-1">Bristol Bisons RFC</a></h1>
		<div id="login_error">That didn't seem to work, please try again.</div>
	<?php else : ?>
		<h1><a href="https://wordpress.org/" title="Powered by WordPress" tabindex="-1">Bristol Bisons RFC</a></h1>
		<p>Please enter the code generated by your mobile app. If you have lost or damaged your phone, you will need to ask the administrator to reset access to your account.</p>
	<?php endif ?>
	<form method="POST">

		<div>
			<label fpr="OTP">
				One Time Password
				<br/>
				<input type="text" name="OTP"/>
			</label>
		</div>
		<div>
			<button type="submit" class="button button-primary button-large">OK</button>
		</div>
	</form>
	<p id="backtoblog"><a href="<?php echo site_url() ?>" title="Are you lost">← Back to Bristol Bisons RFC</a></p>
</div>
</body>
</html>